models/User.php
<?php

namespace app\models;


use app\helpers\God;
use app\modules\matrix\models\UserNodeTrait;
use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * @property string id
 * @property string email
 * @property string hash
 * @property string auth
 * @property string code
 * @property number account
 * @property string password
 * @property string referral_id
 *
 * @property User referral
 */
class User extends ActiveRecord implements IdentityInterface {

    use UserNodeTrait;

    private $_password;
    public $repeat;

    const LOGIN = '/^[a-z][\w\.]{3,22}\w$/';
    const PIN = '/^\d{4}$/';
    const PERFECT = '/^U\d{7,8}$/';

    public static function tableName()
    {
        return 'user';
    }

    public static function primaryKey() {
        return ['id'];
    }

    public function rules() {
        return [
            [['id', 'email', 'referral_id', 'forename', 'surname',
                'patronymic', 'phone', 'skype', 'country', 'postal', 'city', 'address', 'confidant_type',
                'confidant_forename', 'confidant_surname', 'confidant_patronymic', 'pin', 'repeat'], 'required'],
            ['id', 'string'],
            ['email', 'email'],
            [['hash', 'auth', 'code', 'postal'], 'string'],
            [['id', 'referral_id'], 'match', 'pattern' => static::LOGIN],
            ['pin', 'match', 'pattern' => static::PIN],
            ['account', 'default', 'value' => 0],
            ['id', 'unique',
                'targetClass' => 'app\models\User',
                'message' => Yii::t('app', 'This value has already been taken')],
            ['referral_id', 'exist',
                'targetClass' => 'app\models\User',
                'targetAttribute' => 'id',
                'message' => Yii::t('app', 'The referral does not exists')],
            ['perfect_usd', 'match', 'pattern' => static::PERFECT],

        ];
    }
/*
    public function scenarios()
    {
        return [
            'default' => ['id', 'email', 'password', 'referral_id', 'wallet_perfect'],
            'update' => ['email'],
        ];
    }
*/
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'Login'),
            'account' => Yii::t('app', 'Account'),
            'email' => Yii::t('app', 'Email'),
            'hash' => Yii::t('app', 'Hash'),
            'auth' => Yii::t('app', 'Auth'),
            'code' => Yii::t('app', 'Code'),
            'referral_id' => Yii::t('app', 'Referral login'),
            'forename' => Yii::t('app', 'Forename'),
            'surname' => Yii::t('app', 'Surname'),
            'patronymic' => Yii::t('app', 'Patronymic'),
            'phone' => Yii::t('app', 'Phone'),
            'skype' => Yii::t('app', 'Skype'),
            'country' => Yii::t('app', 'Country'),
            'postal' => Yii::t('app', 'Postal'),
            'city' => Yii::t('app', 'City'),
            'address' => Yii::t('app', 'Address'),
            'confidant_type' => Yii::t('app', 'Confidant'),
            'confidant_forename' => Yii::t('app', 'Confidant forename'),
            'confidant_surname' => Yii::t('app', 'Confidant surname'),
            'confidant_patronymic' => Yii::t('app', 'Confidant patronymic'),
            'password' => Yii::t('app', 'Password'),
            'repeat' => Yii::t('app', 'Repeat password'),
            'pin' => Yii::t('app', 'Pin'),
            'perfect_usd' => Yii::t('app', 'Perfect Money'),
            'capture'=>Yii::t('app','Capture')
        ];
    }

    public static function getConfidantTypes() {
        return [
            'father' => Yii::t('app', 'father'),
            'mother' => Yii::t('app', 'mother'),
            'brother' => Yii::t('app', 'brother'),
            'sister' => Yii::t('app', 'sister'),
            'husband' => Yii::t('app', 'husband'),
            'wife' => Yii::t('app', 'wife'),
            'son' => Yii::t('app', 'son'),
            'daughter' => Yii::t('app', 'daughter'),
            'other' => Yii::t('app', 'other')
        ];
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return static::hashAuthKey($this->auth);
    }

    public function validateAuthKey($authKey)
    {
        return static::hashAuthKey($this->auth) == $authKey;
    }

    protected static function hashAuthKey($key)
    {
        $ip = Yii::$app->request->getUserIP();
        if ($ip) {
            $key .= 'devil' . $ip;
        }
        return hash('sha512', $key);
    }

    public function generateAuthKey() {
        $this->auth = Yii::$app->security->generateRandomString(64);
    }

    public function generateCode() {
        $this->code = Yii::$app->security->generateRandomString(64);
    }

    public function setPassword($value) {
        if (!password_verify($value, $this->hash)) {
            $this->_password = $value;
            $this->hash = password_hash($value, PASSWORD_DEFAULT);
            $this->generateAuthKey();
        }
    }

    public function getPassword() {
        return $this->_password;
    }

    public function validatePassword($value) {
        return password_verify($value, $this->hash);
    }

    public function dumpErrors() {
        foreach($this->getErrors() as $name => $message) {
            Yii::$app->session->addFlash($name . ': ' . $message);
        }
    }

    public function sendEmail($params, $template = 'basic') {
        return God::mail($this->email, $template, $params);
    }

    public function getReferral() {
        return $this->hasOne(static::class, ['id' => 'referral_id']);
    }

    public function walletAttributes() {
        return ['perfect_usd'];
    }
}

controllers/UserController.php
<?php

namespace app\controllers;


use app\models\Capture;
use app\models\LoginForm;
use app\models\PasswordForm;
use app\models\RequestForm;
use app\models\User;
use app\models\WalletForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class UserController extends Controller {
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'login', 'logout', 'request', 'reset', 'password', 'reset-auth'],
                'rules' => [
                    [
                        'actions' => ['create', 'login', 'request', 'reset'],
                        'allow' => true,
                        'roles' => ['?']
                    ],
                    [
                        'actions' => ['logout', 'update', 'password', 'reset-auth'],
                        'allow' => true,
                        'roles' => ['@']
                    ],
                ]
            ]
        ];
    }

    public function actionIndex($referral_id = null) {
        if ($referral_id) {
            Yii::$app->layout = 'cabinet';
        }
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider([
                'query' => User::find()->andFilterWhere(['referral_id' => $referral_id]),
                'sort' => [
                    'defaultOrder' => ['id' => SORT_DESC]
                ]
            ])
        ]);
    }

    public function actionLogin() {
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $model->getUser();
            if ($user && $user->validatePassword($model->password)) {
                if (empty($user->auth)) {
                    $user->generateAuthKey();
                    $user->save(true, ['auth']);
                }

                if (Yii::$app->user->login($user)) {
                    $isLocal = Yii::$app->request->getServerName() == parse_url(Yii::$app->request->referrer, PHP_URL_HOST);
                    if (isset($_POST['back']) && $isLocal) {
                        return $this->redirect(Yii::$app->request->referrer);
                    }
                    return Yii::$app->user->can('manage')
                        ? $this->redirect(['/user/index'])
                        : $this->redirect(['view', 'id' => $user->id]);
                }
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
            }
        }

        return $this->render('login', [
            'model' => $model
        ]);
    }

    public function actionLogout($destroy = false) {
        Yii::$app->user->logout($destroy);
        return $this->goHome();
    }

    public function actionResetAuth($id) {
        if (!Yii::$app->user->can('manage') && $id != Yii::$app->user->id) {
            throw new ForbiddenHttpException();
        }
        $model = $this->findModel($id);
        $model->generateAuthKey();
        if ($model->save(false)) {
            Yii::$app->session->addFlash('success', Yii::t('app', 'Logout done'));
        }
        return $this->goHome();
    }

    public function actionCreate($referral_id = null) {
        $model = new User(['referral_id' => $referral_id]);
        Yii::$app->view->title = Yii::t('app', 'Signup');
        return $this->edit($model);
    }

    public function actionUpdate($id = null) {
        $model = $this->findModel($id);
        Yii::$app->view->title = Yii::t('app', 'Update');
        Yii::$app->layout = 'cabinet';
        return $this->edit($model);
    }

    public function actionView($id = null) {
        if (empty($id)) {
            return $this->redirect(['user/view', 'id' => Yii::$app->user->id]);
        }
        $model = $this->findModel($id);
        Yii::$app->layout = 'cabinet';
        return $this->render('view', [
            'model' => $model
        ]);
    }

    public function findModel($id = null) {
        /** @var User $model */
        if ($id) {
            $model = User::findOne($id);
            if (!$model) {
                throw new NotFoundHttpException();
            }
        }
        else {
            $model = Yii::$app->user->identity;
        }
        return $model;
    }

    public function actionPassword($id) {
        if (!Yii::$app->user->can('manage') && $id != Yii::$app->user->id) {
            throw new ForbiddenHttpException();
        }
        $user = $this->findModel($id);
        $model = new PasswordForm();
        if ($this->password($user, $model)) {
            return $this->redirect(['view', 'id' => $id]);
        }
        Yii::$app->layout = 'cabinet';
        return $this->render('password', [
            'model' => $model
        ]);
    }

    public function actionReset($code) {
        /** @var User $user */
        $user = User::findOne(['code' => $code]);
        if (!$user) {
            Yii::$app->session->addFlash('error', Yii::t('app', 'Invalid code'));
            return $this->goHome();
        }
        $model = new PasswordForm();
        $user->code = null;
        if ($this->password($user, $model)) {
            return $this->redirect(['login']);
        }
        return $this->render('password', [
            'model' => $model
        ]);
    }

    public function actionRequest() {
        $model = new RequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $model->getUser();
            if ($user) {
                $user->generateCode();
                if ($user->save(false)) {
                    $url = Url::to(['reset', 'code' => $user->code], true);
                    $content = Yii::t('app', 'To recover your password, open <a href="{url}">this link</a>', [
                        'url' => $url,
                    ]);
                    $user->sendEmail([
                        'subject' => Yii::$app->name . ': ' . Yii::t('app', 'Password reset'),
                        'content' => $content
                    ]);
                    Yii::$app->session->addFlash('info', Yii::t('app', 'Check your mail'));
                    return $this->goHome();
                }
            }

            if (empty($model->id) && empty($model->email)) {
                Yii::$app->session->addFlash('error', Yii::t('app', 'Enter login or email'));
            }
        }

        return $this->render('request', [
            'model' => $model
        ]);
    }

    public function actionWallet($id) {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save(true, $model->walletAttributes())) {
            return $this->redirect(['view', 'id' => $id]);
        }
        Yii::$app->layout = 'cabinet';
        return $this->render('wallet', [
            'model' => $model
        ]);
    }

    public function actionComplete($search) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return User::find()
            ->select('id')
            ->where('id like :id', [
                ':id' => "$search%"
            ])
            ->limit(10)
            ->column();
    }
    protected function edit(User $model) {
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->save(false) && Yii::$app->user->login($model)) {
                $query = new Query();
                $query->select('user_id')->from('capture')->where(['user_id'=>$model->id]);
                $capture = $query->one();
                if(!$capture) {
                    $capture = new Capture();
                    $capture->user_id = $model->id;
                    $capture->content = $model->id." referral page";
                    $capture->save();
                }
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('edit', [
            'model' => $model
        ]);
    }

    protected function password(User $user, PasswordForm $model) {
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user->setPassword($model->password);
            return $user->save(true, ['hash', 'auth', 'code']);
        }
        return false;
    }
}

views/user/edit.php
<?php
/* @var $this yii\web\View */
/* @var $model \app\models\User */

use app\helpers\Country;
use app\models\User;
use app\widgets\Fake;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

if ($model->hasErrors()) {
    echo Html::script('var errors = ' . json_encode($model->getErrors()));
}

?>
<div class="user-edit">
    <?php
    $form = ActiveForm::begin([
        'options' => ['name' => 'User'],
        'fieldConfig' => function(User $model, $attribute) {
            return [
                'template' => '{input}{error}',
                'inputOptions' => [
                    'class' => 'form-control',
                    'placeholder' => $model->attributeLabels()[$attribute]
                ]
            ];
        }
    ]);
    ?>

    <p>
        <?php if (Yii::$app->user->can('manage')): ?>
            <?= Fake::widget() ?>
        <?php endif ?>
    </p>

    <div class="row">
        <div class="col-sm-4">
            <?php if(Yii::$app->controller->action->id != 'update'){ ?>
            <?= $form->field($model, 'referral_id'); } ?>
            <?= $form->field($model, 'id') ?>
            <?= $form->field($model, 'surname') ?>
            <?= $form->field($model, 'forename') ?>
            <?= $form->field($model, 'patronymic') ?>
            <?= $form->field($model, 'skype') ?>
            <?= $form->field($model, 'phone') ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'country')->dropDownList(Country::getCountries()) ?>
            <?= $form->field($model, 'city') ?>
            <?= $form->field($model, 'postal') ?>
            <?= $form->field($model, 'address') ?>
            <?= $form->field($model, 'pin') ?>
            <?= $form->field($model, 'email') ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'password')->passwordInput() ?>
            <?= $form->field($model, 'repeat')->passwordInput() ?>
            <?= $form->field($model, 'confidant_type')->dropDownList(User::getConfidantTypes()) ?>
            <?= $form->field($model, 'confidant_surname') ?>
            <?= $form->field($model, 'confidant_forename') ?>
            <?= $form->field($model, 'confidant_patronymic') ?>
        </div>
    </div>

    <?php if ($model->isNewRecord): ?>
    <p>
        <input type="checkbox" id="agree" />
        <label for="agree">я согласен с условиями компании</label>
    </p>
    <?php endif ?>

    <p class="buttons">
        <?= Html::submitButton($this->title, ['class' => 'btn btn-primary']) ?>
    </p>

    <?php ActiveForm::end(); ?>
</div>

views/user/index.php
<?php

use app\models\User;
use yii\grid\GridView;
use yii\helpers\Html;

/** @var $this yii\web\View */
/** @var \yii\data\ActiveDataProvider $dataProvider */

?>
<div class="user-index">
    <?=  GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'attribute' => 'id',
                'format' => 'html',
                'value' => function(User $model) {
                    return Html::a($model->id, ['index', 'referral_id' => $model->id]);
                }
            ],
            'surname',
            'forename',
            'email',
            'skype',
            'phone',
            [
                'attribute' => 'referral_id',
                'format' => 'html',
                'value' => function(User $model) {
                    return Html::a($model->referral_id, ['index', 'referral_id' => $model->referral_id]);
                }
            ],
            [
//                'label' => Yii::t('app', 'Actions'),
//                'attribute' => 'id',
                'format' => 'html',
                'value' => function(User $model) {
                    $items = [
                        Html::a(' ', ['update', 'id' => $model->id], [
                            'class' => 'fa fa-pencil-square-o',
                            'title' => Yii::t('app', 'Edit')
                        ])
                    ];
                    if ($model->auth) {
                        $items[] = Html::a('', ['/admin/user/login', 'auth' => $model->auth], [
                            'class' => 'fa fa-sign-in',
                            'title' => Yii::t('app', 'Login')
                        ]);
                    }
                    return implode(' ', $items);
                }
            ],
        ]
    ]) ?>
</div>

views/user/login.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\LoginForm */
/* @var $form ActiveForm */

$this->title = Yii::t('app', 'Login');
?>
<div class="user-login">
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= Html::a(Yii::t('app', 'Forgot your password?'), ['/user/request']) ?>
    <?= Html::a(Yii::t('app', 'Sign Up'), ['/user/create']) ?>
    <p>
        <?= Html::submitButton($this->title,['class'=>'btn btn-success']) ?>
    <p>
    <?php ActiveForm::end(); ?>
</div><!-- user-login -->

views/user/password.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/** @var \app\models\PasswordForm $model */
?>
<div class="user-reset">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= $form->field($model, 'repeat')->passwordInput() ?>
    <?= Html::submitButton(Yii::t('app', 'Change')) ?>
    <?php ActiveForm::end() ?>
</div>

views/user/request.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/** @var \app\models\RequestForm $model */
?>
<div class="user-request">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'id') ?>
    <?= $form->field($model, 'email') ?>
    <?= Html::submitButton(Yii::t('app', 'Send Password')) ?>
    <?php ActiveForm::end() ?>
</div>

views/user/view.php
<?php
/* @var $this yii\web\View */
/* @var $model \app\models\User */

use app\helpers\Country;
use app\widgets\Panel;
use yii\helpers\Html;
use yii\widgets\DetailView;

$this->title = $model->id;

function spaces()
{
    return implode(' ', func_get_args());
}

if (Yii::$app->user->can('manage')) {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
}

$attributes = [
    [
        'attribute' => 'account',
        'value' => (float)$model->account
    ],
    [
        'attribute' => 'referral_id',
        'format' => 'html',
        'value' => Html::a($model->referral_id,
            ['view', 'referral_id' => $model->referral_id],
            ['class' => 'value'])
    ],
    'email',
    'skype',
    'phone',
    [
        'attribute' => 'country',
        'value' => $model->country ? Country::decode($model->country) : null
    ],
    'postal',
    'city',
    'address',
    [
        'label' => Yii::t('app', 'Confidant'),
        'value' => spaces($model->confidant_forename, $model->confidant_surname, $model->confidant_patronymic)
    ],
];

?>
<div class="user-view table-block">
    <div>
        <div>
            <div>
                <?= spaces($model->forename, $model->surname, $model->patronymic) ?>
            </div>
        </div>
        <div>
            <div>
                <?= $model->id ?>
            </div>
        </div>
    </div>
    <div>
        <div class="attributes">
            <?= DetailView::widget([
                'model' => $model,
                'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
                'attributes' => $attributes,
                'template' => '<tr><th>{label}</th><td><div>{value}</div></td></tr>'
            ]) ?>
        </div>
        <div class="huylo"></div>
    </div>
    <div>
        <div></div>
        <div></div>
    </div>
</div>

views/user/wallet.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$users_url = ['label' => Yii::t('app', 'Users')];
if (Yii::$app->user->can('manage')) {
    $users_url['url'] = ['index'];
}
$this->params['breadcrumbs'][] = $users_url;
$this->params['breadcrumbs'][] = ['label' => Yii::$app->user->id, 'url' => ['view', 'id' => Yii::$app->user->id]];

/** @var \app\models\User $model */
?>
<div class="user-wallet">
    <?php $form = ActiveForm::begin(); ?>

    <?php
    foreach($model->walletAttributes() as $name) {
        echo $form->field($model, $name);
    }
    ?>

    <?= Html::submitButton(Yii::t('app', 'Save')) ?>

    <?php ActiveForm::end(); ?>
</div>