models/Capture.php
<?php
/**
 * Created by PhpStorm.
 * User: yura
 * Date: 17.02.16
 * Time: 11:15
 */
namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "posts".
 *

 * @property string $user_id
 * @property string $content
 *
 * @property User $user
 */
class Capture extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'capture';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'content'], 'required'],
            [['user_id','content'], 'string'],
        ];
    }

    public static function primaryKey() {
        return ['user_id'];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_id' => Yii::t('app','user'),
            'content' => Yii::t('app','Content'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['user_id' => 'user_id']);
    }
}

controllers/CaptureController.php
<?php
/**
 * Created by PhpStorm.
 * User: yura
 * Date: 17.02.16
 * Time: 11:21
 */
namespace app\controllers;

use Yii;
use app\models\Capture;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use yii\web\ForbiddenHttpException;

/**
 * PostsController implements the CRUD actions for Posts model.
 */
class CaptureController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
//                'actions' => [
//                    'delete' => ['post'],
//                ],
            ],
        ];
    }



    /**
     * Displays a single Posts model.
     * @param string $user_id
     * @return mixed
     */
    public function actionCapturepage($user_id)
    {
        Yii::$app->layout = 'capture';
        $query = new Query();
        $query->select('content,user_id')->from('capture')->where(['user_id'=>$user_id]);
        $capture = $query->one();
        return $this->render('capturepage',[
            'capture'=>$capture
        ]);
    }

    /**
     * Updates an existing Posts model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $user_id
     * @return mixed
     */
    public function actionCaptureedit($user_id)
    {
        Yii::$app->layout = 'cabinet';

        $model = $this->findModel($user_id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->render('captureedit',[
                'model'=> $model,
                'succ' =>true
            ]);

        }
//        $query = new Query();
//        $query->select('capture')->from('user')->where(['id'=>$user_id]);
//        $capture = $query->one();
        return $this->render('captureedit',[
            'model'=> $model
        ]);
    }

    /**
     * Finds the Posts model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $user_id
     * @return Capture the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($user_id)
    {
        if (($model = Capture::findOne($user_id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/capture/captureedit.php
<?php
use dosamigos\ckeditor\CKEditor;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\User;
use yii\widgets\ActiveForm;

/**
 * Created by PhpStorm.
 * User: yura
 * Date: 16.02.16
 * Time: 18:06
 */
?>
<div class="user-edit">
    <?php if(!$create) { ?>
    <label class="control-label"><?= Yii::t('app', 'Link') ?> <a href="<?= Url::to(['capture/capturepage', 'user_id' => $model->user_id], true) ?>" target="_blank"><span
            class="label label-warning"><?= Url::to(['capture/capturepage', 'user_id' => $model->user_id], true) ?></span></a>
    </label>
    <?php
     }
//    if($succ){
//        echo "<div class=\"alert alert-success\" role=\"alert\">".Yii::t('app','Successful')."</div>";
//    }
$form = ActiveForm::begin(['id'=>'capture-form']); ?>
<?= $form->field($model, 'content')->widget(CKEditor::className(), [
    'preset' => 'full'
]) ?>
    <p class="buttons">
        <?= Html::submitButton($create ? Yii::t('app','Create'): Yii::t('app','Update'), ['class' => 'btn btn-primary']) ?>
    </p>

<?php ActiveForm::end(); ?>

views/capture/capturepage.php
<?php
/**
 * Created by PhpStorm.
 * User: yura
 * Date: 16.02.16
 * Time: 9:04
 */
use yii\helpers\Html;
echo '<div class="capture right">'.Html::a(Yii::t('app','Sign Up'),['user/create','referral_id'=>$capture['user_id']]).'</div><br>';
    echo $capture['content'];